name: CI
on:
  push:
    branches:
      - develop-2.x
  pull_request:
    branches:
      - develop-2.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y cmake faketime
      - name: Build PostSRSd
        run: |
          mkdir _build
          cd _build
          cmake .. -DDEVELOPER_BUILD=ON
          make VERBOSE=ON
      - name: Run tests
        run: |
          cd _build
          ctest --output-on-error

